"""Initial migration.

Revision ID: 2225847a20d8
Revises: 1b3127af0eb4
Create Date: 2022-01-11 16:18:01.958732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2225847a20d8'
down_revision = '1b3127af0eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('woringlist', sa.Column('workname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('woringlist', 'workname')
    # ### end Alembic commands ###
